# Generated by Django 2.0.1 on 2018-01-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('sitio_web', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('EST', 'ESTATAL'), ('NAC', 'NACIONAL'), ('INT', 'INTERNACIONAL')], max_length=3)),
            ],
        ),
    ]
