# Generated by Django 2.0.1 on 2018-01-04 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('medio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medio',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario'),
        ),
    ]
