# Generated by Django 2.0.1 on 2018-01-04 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medio', '0002_medio_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medio',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario'),
        ),
    ]
