# Generated by Django 2.0.1 on 2018-01-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medio', '0003_auto_20180104_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medio',
            name='usuario',
        ),
    ]
