# Generated by Django 2.0.1 on 2018-01-05 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20180105_1015'),
        ('medio', '0005_medio_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medio',
            new_name='Palabra',
        ),
    ]
