# Generated by Django 2.0.1 on 2018-01-18 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20180112_1459'),
        ('medio', '0007_auto_20180112_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medio',
            old_name='tn',
            new_name='tipo',
        ),
        migrations.AddField(
            model_name='medio',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario'),
        ),
        migrations.AlterField(
            model_name='medio',
            name='url',
            field=models.URLField(max_length=50),
        ),
    ]
