# Generated by Django 2.0.1 on 2018-01-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medio', '0008_auto_20180118_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medio',
            name='tipo',
            field=models.CharField(choices=[('EST', 'ESTATAL'), ('NAC', 'NACIONAL'), ('INT', 'INTERNACIONAL')], max_length=3),
        ),
    ]
