# Generated by Django 2.0.1 on 2018-01-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20180112_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Rol',
            field=models.CharField(blank=True, choices=[('C', 'Capturista'), ('A', 'Analista'), ('ADM', 'Administrador')], max_length=1, null=True),
        ),
    ]
