# Generated by Django 2.0.1 on 2018-01-29 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuario_rol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Rol',
            new_name='rol',
        ),
    ]
