# Generated by Django 2.0.1 on 2018-01-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20180129_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('C', 'Capturista'), ('A', 'Analista'), ('ADM', 'Administrador')], max_length=3, null=True),
        ),
    ]
