# Generated by Django 2.0.1 on 2018-01-31 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoreo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(max_length=50)),
                ('publicacion', models.CharField(choices=[('POSITIVO', 'POSITIVO'), ('NEUTRAL', 'NEUTRAL'), ('NEGATIVO', 'NEGATIVO')], max_length=8)),
                ('descripcion', models.TextField()),
                ('fecha_publicacion', models.DateField()),
                ('medio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
