# Generated by Django 2.0.1 on 2018-01-31 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20180129_1247'),
        ('monitoreo', '0002_auto_20180131_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoreo',
            name='usuer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario'),
        ),
    ]
