# Generated by Django 2.0.1 on 2018-01-31 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0004_auto_20180131_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoreo',
            name='usuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
