# Generated by Django 2.0.1 on 2018-01-31 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0006_auto_20180131_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitoreo',
            old_name='usuario',
            new_name='medio',
        ),
    ]
