# Generated by Django 2.0.1 on 2018-02-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0006_auto_20180131_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoreo',
            name='fecha_publicacion',
            field=models.DateTimeField(),
        ),
    ]
