# Generated by Django 2.0.1 on 2018-02-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0007_auto_20180202_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoreo',
            name='fecha_publicacion',
            field=models.DateField(),
        ),
    ]
