# Generated by Django 2.0.1 on 2018-02-02 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0007_auto_20180131_1438'),
        ('monitoreo', '0008_auto_20180202_1449'),
    ]

    operations = [
    ]
